# Generated by Django 4.2.5 on 2024-02-29 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coursemanager", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="video_url",
            field=models.URLField(null=True),
        ),
    ]
