# Generated by Django 4.2.5 on 2024-03-02 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("coursemanager", "0003_product_max_students_product_min_students_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="groups_product",
                to="coursemanager.product",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="coursemanager.product",
            ),
        ),
    ]
